const API='/api'; let token=localStorage.novaToken||''; const $=id=>document.getElementById(id);
async function api(p,o={}){const headers={...(token?{Authorization:'Bearer '+token}:{})}; if(!(o.body instanceof FormData)) headers['Content-Type']='application/json'; const r=await fetch(API+p,{...o,headers:{...headers,...(o.headers||{})}}); const d=await r.json().catch(()=>({})); if(!r.ok) throw Error(d.error||'حدث خطأ'); return d;}
function setLoggedIn(on){$('authBox').style.display=on?'none':'block';$('logout').style.display=on?'inline-block':'none';}
async function refresh(){if(!token){setLoggedIn(false);return;} try{const m=await api('/me');setLoggedIn(true);$('account').innerHTML=`الخطة: <b>${m.plan}</b> — اليوم: ${m.usedToday}${m.limit?'/'+m.limit:''}`;$('price').textContent=m.plusPrice; await loadJobs(); if(m.plan==='owner')loadAdmin();}catch{token='';localStorage.removeItem('novaToken');setLoggedIn(false);}}
async function loadJobs(){const jobs=await api('/jobs');$('jobs').innerHTML=jobs.length?jobs.map(j=>`<div class="user"><span>${new Date(j.created_at).toLocaleString('ar-OM')} — ${j.status}</span>${j.video_url?`<a href="${j.video_url}" target="_blank">فيديو</a>`:''}</div>`).join(''):'<p class="muted">لا توجد فيديوهات بعد.</p>';}
$('login').onclick=async()=>{try{const d=await api('/auth/login',{method:'POST',body:JSON.stringify({email:$('email').value,password:$('password').value})});token=d.token;localStorage.novaToken=token;await refresh();}catch(e){alert(e.message)}};
$('register').onclick=async()=>{try{const d=await api('/auth/register',{method:'POST',body:JSON.stringify({email:$('email').value,password:$('password').value})});token=d.token;localStorage.novaToken=token;await refresh();}catch(e){alert(e.message)}};
$('logout').onclick=()=>{token='';localStorage.removeItem('novaToken');setLoggedIn(false);location.reload();};
$('generate').onclick=async()=>{if(!token)return alert('سجّل الدخول أولًا');$('msg').textContent='جاري التوليد...';$('result').innerHTML='';try{const d=await api('/generate',{method:'POST',body:JSON.stringify({prompt:$('prompt').value,mode:$('mode').value,imageUrl:$('image').value||undefined})});$('msg').textContent=d.videoUrl?'تم إنشاء الفيديو بنجاح':'اكتمل الطلب';if(d.videoUrl)$('result').innerHTML=`<video class="video" controls src="${d.videoUrl}"></video><p><a href="${d.videoUrl}" target="_blank">فتح/حفظ الفيديو</a></p>`;await refresh();}catch(e){$('msg').textContent=e.message;}};
$('subscribe').onclick=async()=>{if(!token)return alert('سجّل الدخول أولًا');try{const d=await api('/billing/checkout',{method:'POST'});location.href=d.url;}catch(e){alert(e.message)}};
async function loadAdmin(){const a=$('admin');a.classList.remove('hidden');const o=await api('/admin/overview');$('stats').innerHTML=`المستخدمون: <b>${o.users}</b> — Plus: <b>${o.plus}</b> — الفيديوهات: <b>${o.jobs}</b> — محرك الفيديو: <b>${o.falConfigured?'مفعّل':'غير مفعّل'}</b> — الدفع: <b>${o.stripeConfigured?'مفعّل':'غير مفعّل'}</b>`;$('newPrice').value=o.plusPrice;const users=await api('/admin/users');$('users').innerHTML=users.map(u=>`<div class="user"><span>${u.email} — <b>${u.plan}</b></span><span><button data-id="${u.id}" data-plan="free" class="secondary">Free</button> <button data-id="${u.id}" data-plan="plus">Plus</button></span></div>`).join('');document.querySelectorAll('#users button').forEach(b=>b.onclick=async()=>{await api('/admin/users/'+b.dataset.id+'/plan',{method:'PATCH',body:JSON.stringify({plan:b.dataset.plan})});loadAdmin();});}
$('savePrice').onclick=async()=>{await api('/admin/settings',{method:'POST',body:JSON.stringify({plusPriceLabel:$('newPrice').value})});alert('تم حفظ السعر');refresh();};
setLoggedIn(Boolean(token)); refresh();
